### ISSUE TITLE
vtt/thubnailfolder/thumbnails.json not found

### ISSUE THREAD

**Issue by shubho-acc** [estliberitas/node-thumbnails-webvtt#3]
vtt/SampleVideo_1280x720_10mb/thumbnails.json not found
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by sadi321** [comment]
I have the same issue. Please suggest the solution
